### ISSUE TITLE
Add new sorting algorithms [C++]

### ISSUE THREAD

**Issue by eduardosm7** [eduardosm7/sorting-algorithms#1]

**Comment by yagyanshbhatia** [comment]
hey @eduardosm7 
can you please elaborate which sorting algorithms you need? I'd like to contribute to this project :D 
Also, please Assign me this issue

**Comment by pranikamassey** [comment]
I would like to work o this issue. Can you please elaborate which sorting algorithm is required.

**Comment by eduardosm7** [comment]
Well, at first try to implement any new sorting algorithms in "Algorithms.h", receiving (int* & arr) as the array. Then go to "MyArray.h" and add a case to the switch (line 65) indicating your algorithm. And lastly update "main.cpp" just updating the cout (line 35) with your algorithm. If you have any questions, please let me know :).

**Comment by yagyanshbhatia** [comment]
hey @eduardosm7 can you please check my PR and let me know if you want to suggest any changes. 
I added merge and heap sort, with changes you mentioned.

**Comment by eduardosm7** [comment]
@yagyanshbhatia Thanks a lot for your contributions. Appreciate it! :D
